globalThis.FILL_GAME_POLICY_SNAPSHOT = {
  "boardSize":7,
  "pieceTypes":[
    "cross",
    "xshape",
    "square3",
    "vert",
    "hori"
  ],
  "actionCatalog":{
    "cross":[
      {
        "actionId":0,
        "pieceType":"cross",
        "anchor":[
          0,
          0
        ],
        "mask":"131",
        "cells":[
          [
            0,
            0
          ],
          [
            0,
            1
          ],
          [
            1,
            0
          ]
        ],
        "label":"center=(0,0)"
      },
      {
        "actionId":1,
        "pieceType":"cross",
        "anchor":[
          0,
          1
        ],
        "mask":"263",
        "cells":[
          [
            0,
            0
          ],
          [
            0,
            1
          ],
          [
            0,
            2
          ],
          [
            1,
            1
          ]
        ],
        "label":"center=(0,1)"
      },
      {
        "actionId":2,
        "pieceType":"cross",
        "anchor":[
          0,
          2
        ],
        "mask":"526",
        "cells":[
          [
            0,
            1
          ],
          [
            0,
            2
          ],
          [
            0,
            3
          ],
          [
            1,
            2
          ]
        ],
        "label":"center=(0,2)"
      },
      {
        "actionId":3,
        "pieceType":"cross",
        "anchor":[
          0,
          3
        ],
        "mask":"1052",
        "cells":[
          [
            0,
            2
          ],
          [
            0,
            3
          ],
          [
            0,
            4
          ],
          [
            1,
            3
          ]
        ],
        "label":"center=(0,3)"
      },
      {
        "actionId":4,
        "pieceType":"cross",
        "anchor":[
          0,
          4
        ],
        "mask":"2104",
        "cells":[
          [
            0,
            3
          ],
          [
            0,
            4
          ],
          [
            0,
            5
          ],
          [
            1,
            4
          ]
        ],
        "label":"center=(0,4)"
      },
      {
        "actionId":5,
        "pieceType":"cross",
        "anchor":[
          0,
          5
        ],
        "mask":"4208",
        "cells":[
          [
            0,
            4
          ],
          [
            0,
            5
          ],
          [
            0,
            6
          ],
          [
            1,
            5
          ]
        ],
        "label":"center=(0,5)"
      },
      {
        "actionId":6,
        "pieceType":"cross",
        "anchor":[
          0,
          6
        ],
        "mask":"8288",
        "cells":[
          [
            0,
            5
          ],
          [
            0,
            6
          ],
          [
            1,
            6
          ]
        ],
        "label":"center=(0,6)"
      },
      {
        "actionId":7,
        "pieceType":"cross",
        "anchor":[
          1,
          0
        ],
        "mask":"16769",
        "cells":[
          [
            0,
            0
          ],
          [
            1,
            0
          ],
          [
            1,
            1
          ],
          [
            2,
            0
          ]
        ],
        "label":"center=(1,0)"
      },
      {
        "actionId":8,
        "pieceType":"cross",
        "anchor":[
          1,
          1
        ],
        "mask":"33666",
        "cells":[
          [
            0,
            1
          ],
          [
            1,
            0
          ],
          [
            1,
            1
          ],
          [
            1,
            2
          ],
          [
            2,
            1
          ]
        ],
        "label":"center=(1,1)"
      },
      {
        "actionId":9,
        "pieceType":"cross",
        "anchor":[
          1,
          2
        ],
        "mask":"67332",
        "cells":[
          [
            0,
            2
          ],
          [
            1,
            1
          ],
          [
            1,
            2
          ],
          [
            1,
            3
          ],
          [
            2,
            2
          ]
        ],
        "label":"center=(1,2)"
      },
      {
        "actionId":10,
        "pieceType":"cross",
        "anchor":[
          1,
          3
        ],
        "mask":"134664",
        "cells":[
          [
            0,
            3
          ],
          [
            1,
            2
          ],
          [
            1,
            3
          ],
          [
            1,
            4
          ],
          [
            2,
            3
          ]
        ],
        "label":"center=(1,3)"
      },
      {
        "actionId":11,
        "pieceType":"cross",
        "anchor":[
          1,
          4
        ],
        "mask":"269328",
        "cells":[
          [
            0,
            4
          ],
          [
            1,
            3
          ],
          [
            1,
            4
          ],
          [
            1,
            5
          ],
          [
            2,
            4
          ]
        ],
        "label":"center=(1,4)"
      },
      {
        "actionId":12,
        "pieceType":"cross",
        "anchor":[
          1,
          5
        ],
        "mask":"538656",
        "cells":[
          [
            0,
            5
          ],
          [
            1,
            4
          ],
          [
            1,
            5
          ],
          [
            1,
            6
          ],
          [
            2,
            5
          ]
        ],
        "label":"center=(1,5)"
      },
      {
        "actionId":13,
        "pieceType":"cross",
        "anchor":[
          1,
          6
        ],
        "mask":"1060928",
        "cells":[
          [
            0,
            6
          ],
          [
            1,
            5
          ],
          [
            1,
            6
          ],
          [
            2,
            6
          ]
        ],
        "label":"center=(1,6)"
      },
      {
        "actionId":14,
        "pieceType":"cross",
        "anchor":[
          2,
          0
        ],
        "mask":"2146432",
        "cells":[
          [
            1,
            0
          ],
          [
            2,
            0
          ],
          [
            2,
            1
          ],
          [
            3,
            0
          ]
        ],
        "label":"center=(2,0)"
      },
      {
        "actionId":15,
        "pieceType":"cross",
        "anchor":[
          2,
          1
        ],
        "mask":"4309248",
        "cells":[
          [
            1,
            1
          ],
          [
            2,
            0
          ],
          [
            2,
            1
          ],
          [
            2,
            2
          ],
          [
            3,
            1
          ]
        ],
        "label":"center=(2,1)"
      },
      {
        "actionId":16,
        "pieceType":"cross",
        "anchor":[
          2,
          2
        ],
        "mask":"8618496",
        "cells":[
          [
            1,
            2
          ],
          [
            2,
            1
          ],
          [
            2,
            2
          ],
          [
            2,
            3
          ],
          [
            3,
            2
          ]
        ],
        "label":"center=(2,2)"
      },
      {
        "actionId":17,
        "pieceType":"cross",
        "anchor":[
          2,
          3
        ],
        "mask":"17236992",
        "cells":[
          [
            1,
            3
          ],
          [
            2,
            2
          ],
          [
            2,
            3
          ],
          [
            2,
            4
          ],
          [
            3,
            3
          ]
        ],
        "label":"center=(2,3)"
      },
      {
        "actionId":18,
        "pieceType":"cross",
        "anchor":[
          2,
          4
        ],
        "mask":"34473984",
        "cells":[
          [
            1,
            4
          ],
          [
            2,
            3
          ],
          [
            2,
            4
          ],
          [
            2,
            5
          ],
          [
            3,
            4
          ]
        ],
        "label":"center=(2,4)"
      },
      {
        "actionId":19,
        "pieceType":"cross",
        "anchor":[
          2,
          5
        ],
        "mask":"68947968",
        "cells":[
          [
            1,
            5
          ],
          [
            2,
            4
          ],
          [
            2,
            5
          ],
          [
            2,
            6
          ],
          [
            3,
            5
          ]
        ],
        "label":"center=(2,5)"
      },
      {
        "actionId":20,
        "pieceType":"cross",
        "anchor":[
          2,
          6
        ],
        "mask":"135798784",
        "cells":[
          [
            1,
            6
          ],
          [
            2,
            5
          ],
          [
            2,
            6
          ],
          [
            3,
            6
          ]
        ],
        "label":"center=(2,6)"
      },
      {
        "actionId":21,
        "pieceType":"cross",
        "anchor":[
          3,
          0
        ],
        "mask":"274743296",
        "cells":[
          [
            2,
            0
          ],
          [
            3,
            0
          ],
          [
            3,
            1
          ],
          [
            4,
            0
          ]
        ],
        "label":"center=(3,0)"
      },
      {
        "actionId":22,
        "pieceType":"cross",
        "anchor":[
          3,
          1
        ],
        "mask":"551583744",
        "cells":[
          [
            2,
            1
          ],
          [
            3,
            0
          ],
          [
            3,
            1
          ],
          [
            3,
            2
          ],
          [
            4,
            1
          ]
        ],
        "label":"center=(3,1)"
      },
      {
        "actionId":23,
        "pieceType":"cross",
        "anchor":[
          3,
          2
        ],
        "mask":"1103167488",
        "cells":[
          [
            2,
            2
          ],
          [
            3,
            1
          ],
          [
            3,
            2
          ],
          [
            3,
            3
          ],
          [
            4,
            2
          ]
        ],
        "label":"center=(3,2)"
      },
      {
        "actionId":24,
        "pieceType":"cross",
        "anchor":[
          3,
          3
        ],
        "mask":"2206334976",
        "cells":[
          [
            2,
            3
          ],
          [
            3,
            2
          ],
          [
            3,
            3
          ],
          [
            3,
            4
          ],
          [
            4,
            3
          ]
        ],
        "label":"center=(3,3)"
      },
      {
        "actionId":25,
        "pieceType":"cross",
        "anchor":[
          3,
          4
        ],
        "mask":"4412669952",
        "cells":[
          [
            2,
            4
          ],
          [
            3,
            3
          ],
          [
            3,
            4
          ],
          [
            3,
            5
          ],
          [
            4,
            4
          ]
        ],
        "label":"center=(3,4)"
      },
      {
        "actionId":26,
        "pieceType":"cross",
        "anchor":[
          3,
          5
        ],
        "mask":"8825339904",
        "cells":[
          [
            2,
            5
          ],
          [
            3,
            4
          ],
          [
            3,
            5
          ],
          [
            3,
            6
          ],
          [
            4,
            5
          ]
        ],
        "label":"center=(3,5)"
      },
      {
        "actionId":27,
        "pieceType":"cross",
        "anchor":[
          3,
          6
        ],
        "mask":"17382244352",
        "cells":[
          [
            2,
            6
          ],
          [
            3,
            5
          ],
          [
            3,
            6
          ],
          [
            4,
            6
          ]
        ],
        "label":"center=(3,6)"
      },
      {
        "actionId":28,
        "pieceType":"cross",
        "anchor":[
          4,
          0
        ],
        "mask":"35167141888",
        "cells":[
          [
            3,
            0
          ],
          [
            4,
            0
          ],
          [
            4,
            1
          ],
          [
            5,
            0
          ]
        ],
        "label":"center=(4,0)"
      },
      {
        "actionId":29,
        "pieceType":"cross",
        "anchor":[
          4,
          1
        ],
        "mask":"70602719232",
        "cells":[
          [
            3,
            1
          ],
          [
            4,
            0
          ],
          [
            4,
            1
          ],
          [
            4,
            2
          ],
          [
            5,
            1
          ]
        ],
        "label":"center=(4,1)"
      },
      {
        "actionId":30,
        "pieceType":"cross",
        "anchor":[
          4,
          2
        ],
        "mask":"141205438464",
        "cells":[
          [
            3,
            2
          ],
          [
            4,
            1
          ],
          [
            4,
            2
          ],
          [
            4,
            3
          ],
          [
            5,
            2
          ]
        ],
        "label":"center=(4,2)"
      },
      {
        "actionId":31,
        "pieceType":"cross",
        "anchor":[
          4,
          3
        ],
        "mask":"282410876928",
        "cells":[
          [
            3,
            3
          ],
          [
            4,
            2
          ],
          [
            4,
            3
          ],
          [
            4,
            4
          ],
          [
            5,
            3
          ]
        ],
        "label":"center=(4,3)"
      },
      {
        "actionId":32,
        "pieceType":"cross",
        "anchor":[
          4,
          4
        ],
        "mask":"564821753856",
        "cells":[
          [
            3,
            4
          ],
          [
            4,
            3
          ],
          [
            4,
            4
          ],
          [
            4,
            5
          ],
          [
            5,
            4
          ]
        ],
        "label":"center=(4,4)"
      },
      {
        "actionId":33,
        "pieceType":"cross",
        "anchor":[
          4,
          5
        ],
        "mask":"1129643507712",
        "cells":[
          [
            3,
            5
          ],
          [
            4,
            4
          ],
          [
            4,
            5
          ],
          [
            4,
            6
          ],
          [
            5,
            5
          ]
        ],
        "label":"center=(4,5)"
      },
      {
        "actionId":34,
        "pieceType":"cross",
        "anchor":[
          4,
          6
        ],
        "mask":"2224927277056",
        "cells":[
          [
            3,
            6
          ],
          [
            4,
            5
          ],
          [
            4,
            6
          ],
          [
            5,
            6
          ]
        ],
        "label":"center=(4,6)"
      },
      {
        "actionId":35,
        "pieceType":"cross",
        "anchor":[
          5,
          0
        ],
        "mask":"4501394161664",
        "cells":[
          [
            4,
            0
          ],
          [
            5,
            0
          ],
          [
            5,
            1
          ],
          [
            6,
            0
          ]
        ],
        "label":"center=(5,0)"
      },
      {
        "actionId":36,
        "pieceType":"cross",
        "anchor":[
          5,
          1
        ],
        "mask":"9037148061696",
        "cells":[
          [
            4,
            1
          ],
          [
            5,
            0
          ],
          [
            5,
            1
          ],
          [
            5,
            2
          ],
          [
            6,
            1
          ]
        ],
        "label":"center=(5,1)"
      },
      {
        "actionId":37,
        "pieceType":"cross",
        "anchor":[
          5,
          2
        ],
        "mask":"18074296123392",
        "cells":[
          [
            4,
            2
          ],
          [
            5,
            1
          ],
          [
            5,
            2
          ],
          [
            5,
            3
          ],
          [
            6,
            2
          ]
        ],
        "label":"center=(5,2)"
      },
      {
        "actionId":38,
        "pieceType":"cross",
        "anchor":[
          5,
          3
        ],
        "mask":"36148592246784",
        "cells":[
          [
            4,
            3
          ],
          [
            5,
            2
          ],
          [
            5,
            3
          ],
          [
            5,
            4
          ],
          [
            6,
            3
          ]
        ],
        "label":"center=(5,3)"
      },
      {
        "actionId":39,
        "pieceType":"cross",
        "anchor":[
          5,
          4
        ],
        "mask":"72297184493568",
        "cells":[
          [
            4,
            4
          ],
          [
            5,
            3
          ],
          [
            5,
            4
          ],
          [
            5,
            5
          ],
          [
            6,
            4
          ]
        ],
        "label":"center=(5,4)"
      },
      {
        "actionId":40,
        "pieceType":"cross",
        "anchor":[
          5,
          5
        ],
        "mask":"144594368987136",
        "cells":[
          [
            4,
            5
          ],
          [
            5,
            4
          ],
          [
            5,
            5
          ],
          [
            5,
            6
          ],
          [
            6,
            5
          ]
        ],
        "label":"center=(5,5)"
      },
      {
        "actionId":41,
        "pieceType":"cross",
        "anchor":[
          5,
          6
        ],
        "mask":"284790691463168",
        "cells":[
          [
            4,
            6
          ],
          [
            5,
            5
          ],
          [
            5,
            6
          ],
          [
            6,
            6
          ]
        ],
        "label":"center=(5,6)"
      },
      {
        "actionId":42,
        "pieceType":"cross",
        "anchor":[
          6,
          0
        ],
        "mask":"13228499271680",
        "cells":[
          [
            5,
            0
          ],
          [
            6,
            0
          ],
          [
            6,
            1
          ]
        ],
        "label":"center=(6,0)"
      },
      {
        "actionId":43,
        "pieceType":"cross",
        "anchor":[
          6,
          1
        ],
        "mask":"30855045054464",
        "cells":[
          [
            5,
            1
          ],
          [
            6,
            0
          ],
          [
            6,
            1
          ],
          [
            6,
            2
          ]
        ],
        "label":"center=(6,1)"
      },
      {
        "actionId":44,
        "pieceType":"cross",
        "anchor":[
          6,
          2
        ],
        "mask":"61710090108928",
        "cells":[
          [
            5,
            2
          ],
          [
            6,
            1
          ],
          [
            6,
            2
          ],
          [
            6,
            3
          ]
        ],
        "label":"center=(6,2)"
      },
      {
        "actionId":45,
        "pieceType":"cross",
        "anchor":[
          6,
          3
        ],
        "mask":"123420180217856",
        "cells":[
          [
            5,
            3
          ],
          [
            6,
            2
          ],
          [
            6,
            3
          ],
          [
            6,
            4
          ]
        ],
        "label":"center=(6,3)"
      },
      {
        "actionId":46,
        "pieceType":"cross",
        "anchor":[
          6,
          4
        ],
        "mask":"246840360435712",
        "cells":[
          [
            5,
            4
          ],
          [
            6,
            3
          ],
          [
            6,
            4
          ],
          [
            6,
            5
          ]
        ],
        "label":"center=(6,4)"
      },
      {
        "actionId":47,
        "pieceType":"cross",
        "anchor":[
          6,
          5
        ],
        "mask":"493680720871424",
        "cells":[
          [
            5,
            5
          ],
          [
            6,
            4
          ],
          [
            6,
            5
          ],
          [
            6,
            6
          ]
        ],
        "label":"center=(6,5)"
      },
      {
        "actionId":48,
        "pieceType":"cross",
        "anchor":[
          6,
          6
        ],
        "mask":"424411488321536",
        "cells":[
          [
            5,
            6
          ],
          [
            6,
            5
          ],
          [
            6,
            6
          ]
        ],
        "label":"center=(6,6)"
      }
    ],
    "xshape":[
      {
        "actionId":0,
        "pieceType":"xshape",
        "anchor":[
          0,
          0
        ],
        "mask":"257",
        "cells":[
          [
            0,
            0
          ],
          [
            1,
            1
          ]
        ],
        "label":"center=(0,0)"
      },
      {
        "actionId":1,
        "pieceType":"xshape",
        "anchor":[
          0,
          1
        ],
        "mask":"642",
        "cells":[
          [
            0,
            1
          ],
          [
            1,
            0
          ],
          [
            1,
            2
          ]
        ],
        "label":"center=(0,1)"
      },
      {
        "actionId":2,
        "pieceType":"xshape",
        "anchor":[
          0,
          2
        ],
        "mask":"1284",
        "cells":[
          [
            0,
            2
          ],
          [
            1,
            1
          ],
          [
            1,
            3
          ]
        ],
        "label":"center=(0,2)"
      },
      {
        "actionId":3,
        "pieceType":"xshape",
        "anchor":[
          0,
          3
        ],
        "mask":"2568",
        "cells":[
          [
            0,
            3
          ],
          [
            1,
            2
          ],
          [
            1,
            4
          ]
        ],
        "label":"center=(0,3)"
      },
      {
        "actionId":4,
        "pieceType":"xshape",
        "anchor":[
          0,
          4
        ],
        "mask":"5136",
        "cells":[
          [
            0,
            4
          ],
          [
            1,
            3
          ],
          [
            1,
            5
          ]
        ],
        "label":"center=(0,4)"
      },
      {
        "actionId":5,
        "pieceType":"xshape",
        "anchor":[
          0,
          5
        ],
        "mask":"10272",
        "cells":[
          [
            0,
            5
          ],
          [
            1,
            4
          ],
          [
            1,
            6
          ]
        ],
        "label":"center=(0,5)"
      },
      {
        "actionId":6,
        "pieceType":"xshape",
        "anchor":[
          0,
          6
        ],
        "mask":"4160",
        "cells":[
          [
            0,
            6
          ],
          [
            1,
            5
          ]
        ],
        "label":"center=(0,6)"
      },
      {
        "actionId":7,
        "pieceType":"xshape",
        "anchor":[
          1,
          0
        ],
        "mask":"32898",
        "cells":[
          [
            0,
            1
          ],
          [
            1,
            0
          ],
          [
            2,
            1
          ]
        ],
        "label":"center=(1,0)"
      },
      {
        "actionId":8,
        "pieceType":"xshape",
        "anchor":[
          1,
          1
        ],
        "mask":"82181",
        "cells":[
          [
            0,
            0
          ],
          [
            0,
            2
          ],
          [
            1,
            1
          ],
          [
            2,
            0
          ],
          [
            2,
            2
          ]
        ],
        "label":"center=(1,1)"
      },
      {
        "actionId":9,
        "pieceType":"xshape",
        "anchor":[
          1,
          2
        ],
        "mask":"164362",
        "cells":[
          [
            0,
            1
          ],
          [
            0,
            3
          ],
          [
            1,
            2
          ],
          [
            2,
            1
          ],
          [
            2,
            3
          ]
        ],
        "label":"center=(1,2)"
      },
      {
        "actionId":10,
        "pieceType":"xshape",
        "anchor":[
          1,
          3
        ],
        "mask":"328724",
        "cells":[
          [
            0,
            2
          ],
          [
            0,
            4
          ],
          [
            1,
            3
          ],
          [
            2,
            2
          ],
          [
            2,
            4
          ]
        ],
        "label":"center=(1,3)"
      },
      {
        "actionId":11,
        "pieceType":"xshape",
        "anchor":[
          1,
          4
        ],
        "mask":"657448",
        "cells":[
          [
            0,
            3
          ],
          [
            0,
            5
          ],
          [
            1,
            4
          ],
          [
            2,
            3
          ],
          [
            2,
            5
          ]
        ],
        "label":"center=(1,4)"
      },
      {
        "actionId":12,
        "pieceType":"xshape",
        "anchor":[
          1,
          5
        ],
        "mask":"1314896",
        "cells":[
          [
            0,
            4
          ],
          [
            0,
            6
          ],
          [
            1,
            5
          ],
          [
            2,
            4
          ],
          [
            2,
            6
          ]
        ],
        "label":"center=(1,5)"
      },
      {
        "actionId":13,
        "pieceType":"xshape",
        "anchor":[
          1,
          6
        ],
        "mask":"532512",
        "cells":[
          [
            0,
            5
          ],
          [
            1,
            6
          ],
          [
            2,
            5
          ]
        ],
        "label":"center=(1,6)"
      },
      {
        "actionId":14,
        "pieceType":"xshape",
        "anchor":[
          2,
          0
        ],
        "mask":"4210944",
        "cells":[
          [
            1,
            1
          ],
          [
            2,
            0
          ],
          [
            3,
            1
          ]
        ],
        "label":"center=(2,0)"
      },
      {
        "actionId":15,
        "pieceType":"xshape",
        "anchor":[
          2,
          1
        ],
        "mask":"10519168",
        "cells":[
          [
            1,
            0
          ],
          [
            1,
            2
          ],
          [
            2,
            1
          ],
          [
            3,
            0
          ],
          [
            3,
            2
          ]
        ],
        "label":"center=(2,1)"
      },
      {
        "actionId":16,
        "pieceType":"xshape",
        "anchor":[
          2,
          2
        ],
        "mask":"21038336",
        "cells":[
          [
            1,
            1
          ],
          [
            1,
            3
          ],
          [
            2,
            2
          ],
          [
            3,
            1
          ],
          [
            3,
            3
          ]
        ],
        "label":"center=(2,2)"
      },
      {
        "actionId":17,
        "pieceType":"xshape",
        "anchor":[
          2,
          3
        ],
        "mask":"42076672",
        "cells":[
          [
            1,
            2
          ],
          [
            1,
            4
          ],
          [
            2,
            3
          ],
          [
            3,
            2
          ],
          [
            3,
            4
          ]
        ],
        "label":"center=(2,3)"
      },
      {
        "actionId":18,
        "pieceType":"xshape",
        "anchor":[
          2,
          4
        ],
        "mask":"84153344",
        "cells":[
          [
            1,
            3
          ],
          [
            1,
            5
          ],
          [
            2,
            4
          ],
          [
            3,
            3
          ],
          [
            3,
            5
          ]
        ],
        "label":"center=(2,4)"
      },
      {
        "actionId":19,
        "pieceType":"xshape",
        "anchor":[
          2,
          5
        ],
        "mask":"168306688",
        "cells":[
          [
            1,
            4
          ],
          [
            1,
            6
          ],
          [
            2,
            5
          ],
          [
            3,
            4
          ],
          [
            3,
            6
          ]
        ],
        "label":"center=(2,5)"
      },
      {
        "actionId":20,
        "pieceType":"xshape",
        "anchor":[
          2,
          6
        ],
        "mask":"68161536",
        "cells":[
          [
            1,
            5
          ],
          [
            2,
            6
          ],
          [
            3,
            5
          ]
        ],
        "label":"center=(2,6)"
      },
      {
        "actionId":21,
        "pieceType":"xshape",
        "anchor":[
          3,
          0
        ],
        "mask":"539000832",
        "cells":[
          [
            2,
            1
          ],
          [
            3,
            0
          ],
          [
            4,
            1
          ]
        ],
        "label":"center=(3,0)"
      },
      {
        "actionId":22,
        "pieceType":"xshape",
        "anchor":[
          3,
          1
        ],
        "mask":"1346453504",
        "cells":[
          [
            2,
            0
          ],
          [
            2,
            2
          ],
          [
            3,
            1
          ],
          [
            4,
            0
          ],
          [
            4,
            2
          ]
        ],
        "label":"center=(3,1)"
      },
      {
        "actionId":23,
        "pieceType":"xshape",
        "anchor":[
          3,
          2
        ],
        "mask":"2692907008",
        "cells":[
          [
            2,
            1
          ],
          [
            2,
            3
          ],
          [
            3,
            2
          ],
          [
            4,
            1
          ],
          [
            4,
            3
          ]
        ],
        "label":"center=(3,2)"
      },
      {
        "actionId":24,
        "pieceType":"xshape",
        "anchor":[
          3,
          3
        ],
        "mask":"5385814016",
        "cells":[
          [
            2,
            2
          ],
          [
            2,
            4
          ],
          [
            3,
            3
          ],
          [
            4,
            2
          ],
          [
            4,
            4
          ]
        ],
        "label":"center=(3,3)"
      },
      {
        "actionId":25,
        "pieceType":"xshape",
        "anchor":[
          3,
          4
        ],
        "mask":"10771628032",
        "cells":[
          [
            2,
            3
          ],
          [
            2,
            5
          ],
          [
            3,
            4
          ],
          [
            4,
            3
          ],
          [
            4,
            5
          ]
        ],
        "label":"center=(3,4)"
      },
      {
        "actionId":26,
        "pieceType":"xshape",
        "anchor":[
          3,
          5
        ],
        "mask":"21543256064",
        "cells":[
          [
            2,
            4
          ],
          [
            2,
            6
          ],
          [
            3,
            5
          ],
          [
            4,
            4
          ],
          [
            4,
            6
          ]
        ],
        "label":"center=(3,5)"
      },
      {
        "actionId":27,
        "pieceType":"xshape",
        "anchor":[
          3,
          6
        ],
        "mask":"8724676608",
        "cells":[
          [
            2,
            5
          ],
          [
            3,
            6
          ],
          [
            4,
            5
          ]
        ],
        "label":"center=(3,6)"
      },
      {
        "actionId":28,
        "pieceType":"xshape",
        "anchor":[
          4,
          0
        ],
        "mask":"68992106496",
        "cells":[
          [
            3,
            1
          ],
          [
            4,
            0
          ],
          [
            5,
            1
          ]
        ],
        "label":"center=(4,0)"
      },
      {
        "actionId":29,
        "pieceType":"xshape",
        "anchor":[
          4,
          1
        ],
        "mask":"172346048512",
        "cells":[
          [
            3,
            0
          ],
          [
            3,
            2
          ],
          [
            4,
            1
          ],
          [
            5,
            0
          ],
          [
            5,
            2
          ]
        ],
        "label":"center=(4,1)"
      },
      {
        "actionId":30,
        "pieceType":"xshape",
        "anchor":[
          4,
          2
        ],
        "mask":"344692097024",
        "cells":[
          [
            3,
            1
          ],
          [
            3,
            3
          ],
          [
            4,
            2
          ],
          [
            5,
            1
          ],
          [
            5,
            3
          ]
        ],
        "label":"center=(4,2)"
      },
      {
        "actionId":31,
        "pieceType":"xshape",
        "anchor":[
          4,
          3
        ],
        "mask":"689384194048",
        "cells":[
          [
            3,
            2
          ],
          [
            3,
            4
          ],
          [
            4,
            3
          ],
          [
            5,
            2
          ],
          [
            5,
            4
          ]
        ],
        "label":"center=(4,3)"
      },
      {
        "actionId":32,
        "pieceType":"xshape",
        "anchor":[
          4,
          4
        ],
        "mask":"1378768388096",
        "cells":[
          [
            3,
            3
          ],
          [
            3,
            5
          ],
          [
            4,
            4
          ],
          [
            5,
            3
          ],
          [
            5,
            5
          ]
        ],
        "label":"center=(4,4)"
      },
      {
        "actionId":33,
        "pieceType":"xshape",
        "anchor":[
          4,
          5
        ],
        "mask":"2757536776192",
        "cells":[
          [
            3,
            4
          ],
          [
            3,
            6
          ],
          [
            4,
            5
          ],
          [
            5,
            4
          ],
          [
            5,
            6
          ]
        ],
        "label":"center=(4,5)"
      },
      {
        "actionId":34,
        "pieceType":"xshape",
        "anchor":[
          4,
          6
        ],
        "mask":"1116758605824",
        "cells":[
          [
            3,
            5
          ],
          [
            4,
            6
          ],
          [
            5,
            5
          ]
        ],
        "label":"center=(4,6)"
      },
      {
        "actionId":35,
        "pieceType":"xshape",
        "anchor":[
          5,
          0
        ],
        "mask":"8830989631488",
        "cells":[
          [
            4,
            1
          ],
          [
            5,
            0
          ],
          [
            6,
            1
          ]
        ],
        "label":"center=(5,0)"
      },
      {
        "actionId":36,
        "pieceType":"xshape",
        "anchor":[
          5,
          1
        ],
        "mask":"22060294209536",
        "cells":[
          [
            4,
            0
          ],
          [
            4,
            2
          ],
          [
            5,
            1
          ],
          [
            6,
            0
          ],
          [
            6,
            2
          ]
        ],
        "label":"center=(5,1)"
      },
      {
        "actionId":37,
        "pieceType":"xshape",
        "anchor":[
          5,
          2
        ],
        "mask":"44120588419072",
        "cells":[
          [
            4,
            1
          ],
          [
            4,
            3
          ],
          [
            5,
            2
          ],
          [
            6,
            1
          ],
          [
            6,
            3
          ]
        ],
        "label":"center=(5,2)"
      },
      {
        "actionId":38,
        "pieceType":"xshape",
        "anchor":[
          5,
          3
        ],
        "mask":"88241176838144",
        "cells":[
          [
            4,
            2
          ],
          [
            4,
            4
          ],
          [
            5,
            3
          ],
          [
            6,
            2
          ],
          [
            6,
            4
          ]
        ],
        "label":"center=(5,3)"
      },
      {
        "actionId":39,
        "pieceType":"xshape",
        "anchor":[
          5,
          4
        ],
        "mask":"176482353676288",
        "cells":[
          [
            4,
            3
          ],
          [
            4,
            5
          ],
          [
            5,
            4
          ],
          [
            6,
            3
          ],
          [
            6,
            5
          ]
        ],
        "label":"center=(5,4)"
      },
      {
        "actionId":40,
        "pieceType":"xshape",
        "anchor":[
          5,
          5
        ],
        "mask":"352964707352576",
        "cells":[
          [
            4,
            4
          ],
          [
            4,
            6
          ],
          [
            5,
            5
          ],
          [
            6,
            4
          ],
          [
            6,
            6
          ]
        ],
        "label":"center=(5,5)"
      },
      {
        "actionId":41,
        "pieceType":"xshape",
        "anchor":[
          5,
          6
        ],
        "mask":"142945101545472",
        "cells":[
          [
            4,
            5
          ],
          [
            5,
            6
          ],
          [
            6,
            5
          ]
        ],
        "label":"center=(5,6)"
      },
      {
        "actionId":42,
        "pieceType":"xshape",
        "anchor":[
          6,
          0
        ],
        "mask":"4466765987840",
        "cells":[
          [
            5,
            1
          ],
          [
            6,
            0
          ]
        ],
        "label":"center=(6,0)"
      },
      {
        "actionId":43,
        "pieceType":"xshape",
        "anchor":[
          6,
          1
        ],
        "mask":"8967891714048",
        "cells":[
          [
            5,
            0
          ],
          [
            5,
            2
          ],
          [
            6,
            1
          ]
        ],
        "label":"center=(6,1)"
      },
      {
        "actionId":44,
        "pieceType":"xshape",
        "anchor":[
          6,
          2
        ],
        "mask":"17935783428096",
        "cells":[
          [
            5,
            1
          ],
          [
            5,
            3
          ],
          [
            6,
            2
          ]
        ],
        "label":"center=(6,2)"
      },
      {
        "actionId":45,
        "pieceType":"xshape",
        "anchor":[
          6,
          3
        ],
        "mask":"35871566856192",
        "cells":[
          [
            5,
            2
          ],
          [
            5,
            4
          ],
          [
            6,
            3
          ]
        ],
        "label":"center=(6,3)"
      },
      {
        "actionId":46,
        "pieceType":"xshape",
        "anchor":[
          6,
          4
        ],
        "mask":"71743133712384",
        "cells":[
          [
            5,
            3
          ],
          [
            5,
            5
          ],
          [
            6,
            4
          ]
        ],
        "label":"center=(6,4)"
      },
      {
        "actionId":47,
        "pieceType":"xshape",
        "anchor":[
          6,
          5
        ],
        "mask":"143486267424768",
        "cells":[
          [
            5,
            4
          ],
          [
            5,
            6
          ],
          [
            6,
            5
          ]
        ],
        "label":"center=(6,5)"
      },
      {
        "actionId":48,
        "pieceType":"xshape",
        "anchor":[
          6,
          6
        ],
        "mask":"282574488338432",
        "cells":[
          [
            5,
            5
          ],
          [
            6,
            6
          ]
        ],
        "label":"center=(6,6)"
      }
    ],
    "square3":[
      {
        "actionId":0,
        "pieceType":"square3",
        "anchor":[
          0,
          0
        ],
        "mask":"387",
        "cells":[
          [
            0,
            0
          ],
          [
            0,
            1
          ],
          [
            1,
            0
          ],
          [
            1,
            1
          ]
        ],
        "label":"center=(0,0)"
      },
      {
        "actionId":1,
        "pieceType":"square3",
        "anchor":[
          0,
          1
        ],
        "mask":"903",
        "cells":[
          [
            0,
            0
          ],
          [
            0,
            1
          ],
          [
            0,
            2
          ],
          [
            1,
            0
          ],
          [
            1,
            1
          ],
          [
            1,
            2
          ]
        ],
        "label":"center=(0,1)"
      },
      {
        "actionId":2,
        "pieceType":"square3",
        "anchor":[
          0,
          2
        ],
        "mask":"1806",
        "cells":[
          [
            0,
            1
          ],
          [
            0,
            2
          ],
          [
            0,
            3
          ],
          [
            1,
            1
          ],
          [
            1,
            2
          ],
          [
            1,
            3
          ]
        ],
        "label":"center=(0,2)"
      },
      {
        "actionId":3,
        "pieceType":"square3",
        "anchor":[
          0,
          3
        ],
        "mask":"3612",
        "cells":[
          [
            0,
            2
          ],
          [
            0,
            3
          ],
          [
            0,
            4
          ],
          [
            1,
            2
          ],
          [
            1,
            3
          ],
          [
            1,
            4
          ]
        ],
        "label":"center=(0,3)"
      },
      {
        "actionId":4,
        "pieceType":"square3",
        "anchor":[
          0,
          4
        ],
        "mask":"7224",
        "cells":[
          [
            0,
            3
          ],
          [
            0,
            4
          ],
          [
            0,
            5
          ],
          [
            1,
            3
          ],
          [
            1,
            4
          ],
          [
            1,
            5
          ]
        ],
        "label":"center=(0,4)"
      },
      {
        "actionId":5,
        "pieceType":"square3",
        "anchor":[
          0,
          5
        ],
        "mask":"14448",
        "cells":[
          [
            0,
            4
          ],
          [
            0,
            5
          ],
          [
            0,
            6
          ],
          [
            1,
            4
          ],
          [
            1,
            5
          ],
          [
            1,
            6
          ]
        ],
        "label":"center=(0,5)"
      },
      {
        "actionId":6,
        "pieceType":"square3",
        "anchor":[
          0,
          6
        ],
        "mask":"12384",
        "cells":[
          [
            0,
            5
          ],
          [
            0,
            6
          ],
          [
            1,
            5
          ],
          [
            1,
            6
          ]
        ],
        "label":"center=(0,6)"
      },
      {
        "actionId":7,
        "pieceType":"square3",
        "anchor":[
          1,
          0
        ],
        "mask":"49539",
        "cells":[
          [
            0,
            0
          ],
          [
            0,
            1
          ],
          [
            1,
            0
          ],
          [
            1,
            1
          ],
          [
            2,
            0
          ],
          [
            2,
            1
          ]
        ],
        "label":"center=(1,0)"
      },
      {
        "actionId":8,
        "pieceType":"square3",
        "anchor":[
          1,
          1
        ],
        "mask":"115591",
        "cells":[
          [
            0,
            0
          ],
          [
            0,
            1
          ],
          [
            0,
            2
          ],
          [
            1,
            0
          ],
          [
            1,
            1
          ],
          [
            1,
            2
          ],
          [
            2,
            0
          ],
          [
            2,
            1
          ],
          [
            2,
            2
          ]
        ],
        "label":"center=(1,1)"
      },
      {
        "actionId":9,
        "pieceType":"square3",
        "anchor":[
          1,
          2
        ],
        "mask":"231182",
        "cells":[
          [
            0,
            1
          ],
          [
            0,
            2
          ],
          [
            0,
            3
          ],
          [
            1,
            1
          ],
          [
            1,
            2
          ],
          [
            1,
            3
          ],
          [
            2,
            1
          ],
          [
            2,
            2
          ],
          [
            2,
            3
          ]
        ],
        "label":"center=(1,2)"
      },
      {
        "actionId":10,
        "pieceType":"square3",
        "anchor":[
          1,
          3
        ],
        "mask":"462364",
        "cells":[
          [
            0,
            2
          ],
          [
            0,
            3
          ],
          [
            0,
            4
          ],
          [
            1,
            2
          ],
          [
            1,
            3
          ],
          [
            1,
            4
          ],
          [
            2,
            2
          ],
          [
            2,
            3
          ],
          [
            2,
            4
          ]
        ],
        "label":"center=(1,3)"
      },
      {
        "actionId":11,
        "pieceType":"square3",
        "anchor":[
          1,
          4
        ],
        "mask":"924728",
        "cells":[
          [
            0,
            3
          ],
          [
            0,
            4
          ],
          [
            0,
            5
          ],
          [
            1,
            3
          ],
          [
            1,
            4
          ],
          [
            1,
            5
          ],
          [
            2,
            3
          ],
          [
            2,
            4
          ],
          [
            2,
            5
          ]
        ],
        "label":"center=(1,4)"
      },
      {
        "actionId":12,
        "pieceType":"square3",
        "anchor":[
          1,
          5
        ],
        "mask":"1849456",
        "cells":[
          [
            0,
            4
          ],
          [
            0,
            5
          ],
          [
            0,
            6
          ],
          [
            1,
            4
          ],
          [
            1,
            5
          ],
          [
            1,
            6
          ],
          [
            2,
            4
          ],
          [
            2,
            5
          ],
          [
            2,
            6
          ]
        ],
        "label":"center=(1,5)"
      },
      {
        "actionId":13,
        "pieceType":"square3",
        "anchor":[
          1,
          6
        ],
        "mask":"1585248",
        "cells":[
          [
            0,
            5
          ],
          [
            0,
            6
          ],
          [
            1,
            5
          ],
          [
            1,
            6
          ],
          [
            2,
            5
          ],
          [
            2,
            6
          ]
        ],
        "label":"center=(1,6)"
      },
      {
        "actionId":14,
        "pieceType":"square3",
        "anchor":[
          2,
          0
        ],
        "mask":"6340992",
        "cells":[
          [
            1,
            0
          ],
          [
            1,
            1
          ],
          [
            2,
            0
          ],
          [
            2,
            1
          ],
          [
            3,
            0
          ],
          [
            3,
            1
          ]
        ],
        "label":"center=(2,0)"
      },
      {
        "actionId":15,
        "pieceType":"square3",
        "anchor":[
          2,
          1
        ],
        "mask":"14795648",
        "cells":[
          [
            1,
            0
          ],
          [
            1,
            1
          ],
          [
            1,
            2
          ],
          [
            2,
            0
          ],
          [
            2,
            1
          ],
          [
            2,
            2
          ],
          [
            3,
            0
          ],
          [
            3,
            1
          ],
          [
            3,
            2
          ]
        ],
        "label":"center=(2,1)"
      },
      {
        "actionId":16,
        "pieceType":"square3",
        "anchor":[
          2,
          2
        ],
        "mask":"29591296",
        "cells":[
          [
            1,
            1
          ],
          [
            1,
            2
          ],
          [
            1,
            3
          ],
          [
            2,
            1
          ],
          [
            2,
            2
          ],
          [
            2,
            3
          ],
          [
            3,
            1
          ],
          [
            3,
            2
          ],
          [
            3,
            3
          ]
        ],
        "label":"center=(2,2)"
      },
      {
        "actionId":17,
        "pieceType":"square3",
        "anchor":[
          2,
          3
        ],
        "mask":"59182592",
        "cells":[
          [
            1,
            2
          ],
          [
            1,
            3
          ],
          [
            1,
            4
          ],
          [
            2,
            2
          ],
          [
            2,
            3
          ],
          [
            2,
            4
          ],
          [
            3,
            2
          ],
          [
            3,
            3
          ],
          [
            3,
            4
          ]
        ],
        "label":"center=(2,3)"
      },
      {
        "actionId":18,
        "pieceType":"square3",
        "anchor":[
          2,
          4
        ],
        "mask":"118365184",
        "cells":[
          [
            1,
            3
          ],
          [
            1,
            4
          ],
          [
            1,
            5
          ],
          [
            2,
            3
          ],
          [
            2,
            4
          ],
          [
            2,
            5
          ],
          [
            3,
            3
          ],
          [
            3,
            4
          ],
          [
            3,
            5
          ]
        ],
        "label":"center=(2,4)"
      },
      {
        "actionId":19,
        "pieceType":"square3",
        "anchor":[
          2,
          5
        ],
        "mask":"236730368",
        "cells":[
          [
            1,
            4
          ],
          [
            1,
            5
          ],
          [
            1,
            6
          ],
          [
            2,
            4
          ],
          [
            2,
            5
          ],
          [
            2,
            6
          ],
          [
            3,
            4
          ],
          [
            3,
            5
          ],
          [
            3,
            6
          ]
        ],
        "label":"center=(2,5)"
      },
      {
        "actionId":20,
        "pieceType":"square3",
        "anchor":[
          2,
          6
        ],
        "mask":"202911744",
        "cells":[
          [
            1,
            5
          ],
          [
            1,
            6
          ],
          [
            2,
            5
          ],
          [
            2,
            6
          ],
          [
            3,
            5
          ],
          [
            3,
            6
          ]
        ],
        "label":"center=(2,6)"
      },
      {
        "actionId":21,
        "pieceType":"square3",
        "anchor":[
          3,
          0
        ],
        "mask":"811646976",
        "cells":[
          [
            2,
            0
          ],
          [
            2,
            1
          ],
          [
            3,
            0
          ],
          [
            3,
            1
          ],
          [
            4,
            0
          ],
          [
            4,
            1
          ]
        ],
        "label":"center=(3,0)"
      },
      {
        "actionId":22,
        "pieceType":"square3",
        "anchor":[
          3,
          1
        ],
        "mask":"1893842944",
        "cells":[
          [
            2,
            0
          ],
          [
            2,
            1
          ],
          [
            2,
            2
          ],
          [
            3,
            0
          ],
          [
            3,
            1
          ],
          [
            3,
            2
          ],
          [
            4,
            0
          ],
          [
            4,
            1
          ],
          [
            4,
            2
          ]
        ],
        "label":"center=(3,1)"
      },
      {
        "actionId":23,
        "pieceType":"square3",
        "anchor":[
          3,
          2
        ],
        "mask":"3787685888",
        "cells":[
          [
            2,
            1
          ],
          [
            2,
            2
          ],
          [
            2,
            3
          ],
          [
            3,
            1
          ],
          [
            3,
            2
          ],
          [
            3,
            3
          ],
          [
            4,
            1
          ],
          [
            4,
            2
          ],
          [
            4,
            3
          ]
        ],
        "label":"center=(3,2)"
      },
      {
        "actionId":24,
        "pieceType":"square3",
        "anchor":[
          3,
          3
        ],
        "mask":"7575371776",
        "cells":[
          [
            2,
            2
          ],
          [
            2,
            3
          ],
          [
            2,
            4
          ],
          [
            3,
            2
          ],
          [
            3,
            3
          ],
          [
            3,
            4
          ],
          [
            4,
            2
          ],
          [
            4,
            3
          ],
          [
            4,
            4
          ]
        ],
        "label":"center=(3,3)"
      },
      {
        "actionId":25,
        "pieceType":"square3",
        "anchor":[
          3,
          4
        ],
        "mask":"15150743552",
        "cells":[
          [
            2,
            3
          ],
          [
            2,
            4
          ],
          [
            2,
            5
          ],
          [
            3,
            3
          ],
          [
            3,
            4
          ],
          [
            3,
            5
          ],
          [
            4,
            3
          ],
          [
            4,
            4
          ],
          [
            4,
            5
          ]
        ],
        "label":"center=(3,4)"
      },
      {
        "actionId":26,
        "pieceType":"square3",
        "anchor":[
          3,
          5
        ],
        "mask":"30301487104",
        "cells":[
          [
            2,
            4
          ],
          [
            2,
            5
          ],
          [
            2,
            6
          ],
          [
            3,
            4
          ],
          [
            3,
            5
          ],
          [
            3,
            6
          ],
          [
            4,
            4
          ],
          [
            4,
            5
          ],
          [
            4,
            6
          ]
        ],
        "label":"center=(3,5)"
      },
      {
        "actionId":27,
        "pieceType":"square3",
        "anchor":[
          3,
          6
        ],
        "mask":"25972703232",
        "cells":[
          [
            2,
            5
          ],
          [
            2,
            6
          ],
          [
            3,
            5
          ],
          [
            3,
            6
          ],
          [
            4,
            5
          ],
          [
            4,
            6
          ]
        ],
        "label":"center=(3,6)"
      },
      {
        "actionId":28,
        "pieceType":"square3",
        "anchor":[
          4,
          0
        ],
        "mask":"103890812928",
        "cells":[
          [
            3,
            0
          ],
          [
            3,
            1
          ],
          [
            4,
            0
          ],
          [
            4,
            1
          ],
          [
            5,
            0
          ],
          [
            5,
            1
          ]
        ],
        "label":"center=(4,0)"
      },
      {
        "actionId":29,
        "pieceType":"square3",
        "anchor":[
          4,
          1
        ],
        "mask":"242411896832",
        "cells":[
          [
            3,
            0
          ],
          [
            3,
            1
          ],
          [
            3,
            2
          ],
          [
            4,
            0
          ],
          [
            4,
            1
          ],
          [
            4,
            2
          ],
          [
            5,
            0
          ],
          [
            5,
            1
          ],
          [
            5,
            2
          ]
        ],
        "label":"center=(4,1)"
      },
      {
        "actionId":30,
        "pieceType":"square3",
        "anchor":[
          4,
          2
        ],
        "mask":"484823793664",
        "cells":[
          [
            3,
            1
          ],
          [
            3,
            2
          ],
          [
            3,
            3
          ],
          [
            4,
            1
          ],
          [
            4,
            2
          ],
          [
            4,
            3
          ],
          [
            5,
            1
          ],
          [
            5,
            2
          ],
          [
            5,
            3
          ]
        ],
        "label":"center=(4,2)"
      },
      {
        "actionId":31,
        "pieceType":"square3",
        "anchor":[
          4,
          3
        ],
        "mask":"969647587328",
        "cells":[
          [
            3,
            2
          ],
          [
            3,
            3
          ],
          [
            3,
            4
          ],
          [
            4,
            2
          ],
          [
            4,
            3
          ],
          [
            4,
            4
          ],
          [
            5,
            2
          ],
          [
            5,
            3
          ],
          [
            5,
            4
          ]
        ],
        "label":"center=(4,3)"
      },
      {
        "actionId":32,
        "pieceType":"square3",
        "anchor":[
          4,
          4
        ],
        "mask":"1939295174656",
        "cells":[
          [
            3,
            3
          ],
          [
            3,
            4
          ],
          [
            3,
            5
          ],
          [
            4,
            3
          ],
          [
            4,
            4
          ],
          [
            4,
            5
          ],
          [
            5,
            3
          ],
          [
            5,
            4
          ],
          [
            5,
            5
          ]
        ],
        "label":"center=(4,4)"
      },
      {
        "actionId":33,
        "pieceType":"square3",
        "anchor":[
          4,
          5
        ],
        "mask":"3878590349312",
        "cells":[
          [
            3,
            4
          ],
          [
            3,
            5
          ],
          [
            3,
            6
          ],
          [
            4,
            4
          ],
          [
            4,
            5
          ],
          [
            4,
            6
          ],
          [
            5,
            4
          ],
          [
            5,
            5
          ],
          [
            5,
            6
          ]
        ],
        "label":"center=(4,5)"
      },
      {
        "actionId":34,
        "pieceType":"square3",
        "anchor":[
          4,
          6
        ],
        "mask":"3324506013696",
        "cells":[
          [
            3,
            5
          ],
          [
            3,
            6
          ],
          [
            4,
            5
          ],
          [
            4,
            6
          ],
          [
            5,
            5
          ],
          [
            5,
            6
          ]
        ],
        "label":"center=(4,6)"
      },
      {
        "actionId":35,
        "pieceType":"square3",
        "anchor":[
          5,
          0
        ],
        "mask":"13298024054784",
        "cells":[
          [
            4,
            0
          ],
          [
            4,
            1
          ],
          [
            5,
            0
          ],
          [
            5,
            1
          ],
          [
            6,
            0
          ],
          [
            6,
            1
          ]
        ],
        "label":"center=(5,0)"
      },
      {
        "actionId":36,
        "pieceType":"square3",
        "anchor":[
          5,
          1
        ],
        "mask":"31028722794496",
        "cells":[
          [
            4,
            0
          ],
          [
            4,
            1
          ],
          [
            4,
            2
          ],
          [
            5,
            0
          ],
          [
            5,
            1
          ],
          [
            5,
            2
          ],
          [
            6,
            0
          ],
          [
            6,
            1
          ],
          [
            6,
            2
          ]
        ],
        "label":"center=(5,1)"
      },
      {
        "actionId":37,
        "pieceType":"square3",
        "anchor":[
          5,
          2
        ],
        "mask":"62057445588992",
        "cells":[
          [
            4,
            1
          ],
          [
            4,
            2
          ],
          [
            4,
            3
          ],
          [
            5,
            1
          ],
          [
            5,
            2
          ],
          [
            5,
            3
          ],
          [
            6,
            1
          ],
          [
            6,
            2
          ],
          [
            6,
            3
          ]
        ],
        "label":"center=(5,2)"
      },
      {
        "actionId":38,
        "pieceType":"square3",
        "anchor":[
          5,
          3
        ],
        "mask":"124114891177984",
        "cells":[
          [
            4,
            2
          ],
          [
            4,
            3
          ],
          [
            4,
            4
          ],
          [
            5,
            2
          ],
          [
            5,
            3
          ],
          [
            5,
            4
          ],
          [
            6,
            2
          ],
          [
            6,
            3
          ],
          [
            6,
            4
          ]
        ],
        "label":"center=(5,3)"
      },
      {
        "actionId":39,
        "pieceType":"square3",
        "anchor":[
          5,
          4
        ],
        "mask":"248229782355968",
        "cells":[
          [
            4,
            3
          ],
          [
            4,
            4
          ],
          [
            4,
            5
          ],
          [
            5,
            3
          ],
          [
            5,
            4
          ],
          [
            5,
            5
          ],
          [
            6,
            3
          ],
          [
            6,
            4
          ],
          [
            6,
            5
          ]
        ],
        "label":"center=(5,4)"
      },
      {
        "actionId":40,
        "pieceType":"square3",
        "anchor":[
          5,
          5
        ],
        "mask":"496459564711936",
        "cells":[
          [
            4,
            4
          ],
          [
            4,
            5
          ],
          [
            4,
            6
          ],
          [
            5,
            4
          ],
          [
            5,
            5
          ],
          [
            5,
            6
          ],
          [
            6,
            4
          ],
          [
            6,
            5
          ],
          [
            6,
            6
          ]
        ],
        "label":"center=(5,5)"
      },
      {
        "actionId":41,
        "pieceType":"square3",
        "anchor":[
          5,
          6
        ],
        "mask":"425536769753088",
        "cells":[
          [
            4,
            5
          ],
          [
            4,
            6
          ],
          [
            5,
            5
          ],
          [
            5,
            6
          ],
          [
            6,
            5
          ],
          [
            6,
            6
          ]
        ],
        "label":"center=(5,6)"
      },
      {
        "actionId":42,
        "pieceType":"square3",
        "anchor":[
          6,
          0
        ],
        "mask":"13297218748416",
        "cells":[
          [
            5,
            0
          ],
          [
            5,
            1
          ],
          [
            6,
            0
          ],
          [
            6,
            1
          ]
        ],
        "label":"center=(6,0)"
      },
      {
        "actionId":43,
        "pieceType":"square3",
        "anchor":[
          6,
          1
        ],
        "mask":"31026843746304",
        "cells":[
          [
            5,
            0
          ],
          [
            5,
            1
          ],
          [
            5,
            2
          ],
          [
            6,
            0
          ],
          [
            6,
            1
          ],
          [
            6,
            2
          ]
        ],
        "label":"center=(6,1)"
      },
      {
        "actionId":44,
        "pieceType":"square3",
        "anchor":[
          6,
          2
        ],
        "mask":"62053687492608",
        "cells":[
          [
            5,
            1
          ],
          [
            5,
            2
          ],
          [
            5,
            3
          ],
          [
            6,
            1
          ],
          [
            6,
            2
          ],
          [
            6,
            3
          ]
        ],
        "label":"center=(6,2)"
      },
      {
        "actionId":45,
        "pieceType":"square3",
        "anchor":[
          6,
          3
        ],
        "mask":"124107374985216",
        "cells":[
          [
            5,
            2
          ],
          [
            5,
            3
          ],
          [
            5,
            4
          ],
          [
            6,
            2
          ],
          [
            6,
            3
          ],
          [
            6,
            4
          ]
        ],
        "label":"center=(6,3)"
      },
      {
        "actionId":46,
        "pieceType":"square3",
        "anchor":[
          6,
          4
        ],
        "mask":"248214749970432",
        "cells":[
          [
            5,
            3
          ],
          [
            5,
            4
          ],
          [
            5,
            5
          ],
          [
            6,
            3
          ],
          [
            6,
            4
          ],
          [
            6,
            5
          ]
        ],
        "label":"center=(6,4)"
      },
      {
        "actionId":47,
        "pieceType":"square3",
        "anchor":[
          6,
          5
        ],
        "mask":"496429499940864",
        "cells":[
          [
            5,
            4
          ],
          [
            5,
            5
          ],
          [
            5,
            6
          ],
          [
            6,
            4
          ],
          [
            6,
            5
          ],
          [
            6,
            6
          ]
        ],
        "label":"center=(6,5)"
      },
      {
        "actionId":48,
        "pieceType":"square3",
        "anchor":[
          6,
          6
        ],
        "mask":"425510999949312",
        "cells":[
          [
            5,
            5
          ],
          [
            5,
            6
          ],
          [
            6,
            5
          ],
          [
            6,
            6
          ]
        ],
        "label":"center=(6,6)"
      }
    ],
    "vert":[
      {
        "actionId":0,
        "pieceType":"vert",
        "anchor":[
          0,
          0
        ],
        "mask":"4432676798593",
        "cells":[
          [
            0,
            0
          ],
          [
            1,
            0
          ],
          [
            2,
            0
          ],
          [
            3,
            0
          ],
          [
            4,
            0
          ],
          [
            5,
            0
          ],
          [
            6,
            0
          ]
        ],
        "label":"col=0"
      },
      {
        "actionId":1,
        "pieceType":"vert",
        "anchor":[
          0,
          1
        ],
        "mask":"8865353597186",
        "cells":[
          [
            0,
            1
          ],
          [
            1,
            1
          ],
          [
            2,
            1
          ],
          [
            3,
            1
          ],
          [
            4,
            1
          ],
          [
            5,
            1
          ],
          [
            6,
            1
          ]
        ],
        "label":"col=1"
      },
      {
        "actionId":2,
        "pieceType":"vert",
        "anchor":[
          0,
          2
        ],
        "mask":"17730707194372",
        "cells":[
          [
            0,
            2
          ],
          [
            1,
            2
          ],
          [
            2,
            2
          ],
          [
            3,
            2
          ],
          [
            4,
            2
          ],
          [
            5,
            2
          ],
          [
            6,
            2
          ]
        ],
        "label":"col=2"
      },
      {
        "actionId":3,
        "pieceType":"vert",
        "anchor":[
          0,
          3
        ],
        "mask":"35461414388744",
        "cells":[
          [
            0,
            3
          ],
          [
            1,
            3
          ],
          [
            2,
            3
          ],
          [
            3,
            3
          ],
          [
            4,
            3
          ],
          [
            5,
            3
          ],
          [
            6,
            3
          ]
        ],
        "label":"col=3"
      },
      {
        "actionId":4,
        "pieceType":"vert",
        "anchor":[
          0,
          4
        ],
        "mask":"70922828777488",
        "cells":[
          [
            0,
            4
          ],
          [
            1,
            4
          ],
          [
            2,
            4
          ],
          [
            3,
            4
          ],
          [
            4,
            4
          ],
          [
            5,
            4
          ],
          [
            6,
            4
          ]
        ],
        "label":"col=4"
      },
      {
        "actionId":5,
        "pieceType":"vert",
        "anchor":[
          0,
          5
        ],
        "mask":"141845657554976",
        "cells":[
          [
            0,
            5
          ],
          [
            1,
            5
          ],
          [
            2,
            5
          ],
          [
            3,
            5
          ],
          [
            4,
            5
          ],
          [
            5,
            5
          ],
          [
            6,
            5
          ]
        ],
        "label":"col=5"
      },
      {
        "actionId":6,
        "pieceType":"vert",
        "anchor":[
          0,
          6
        ],
        "mask":"283691315109952",
        "cells":[
          [
            0,
            6
          ],
          [
            1,
            6
          ],
          [
            2,
            6
          ],
          [
            3,
            6
          ],
          [
            4,
            6
          ],
          [
            5,
            6
          ],
          [
            6,
            6
          ]
        ],
        "label":"col=6"
      }
    ],
    "hori":[
      {
        "actionId":0,
        "pieceType":"hori",
        "anchor":[
          0,
          0
        ],
        "mask":"127",
        "cells":[
          [
            0,
            0
          ],
          [
            0,
            1
          ],
          [
            0,
            2
          ],
          [
            0,
            3
          ],
          [
            0,
            4
          ],
          [
            0,
            5
          ],
          [
            0,
            6
          ]
        ],
        "label":"row=0"
      },
      {
        "actionId":1,
        "pieceType":"hori",
        "anchor":[
          1,
          0
        ],
        "mask":"16256",
        "cells":[
          [
            1,
            0
          ],
          [
            1,
            1
          ],
          [
            1,
            2
          ],
          [
            1,
            3
          ],
          [
            1,
            4
          ],
          [
            1,
            5
          ],
          [
            1,
            6
          ]
        ],
        "label":"row=1"
      },
      {
        "actionId":2,
        "pieceType":"hori",
        "anchor":[
          2,
          0
        ],
        "mask":"2080768",
        "cells":[
          [
            2,
            0
          ],
          [
            2,
            1
          ],
          [
            2,
            2
          ],
          [
            2,
            3
          ],
          [
            2,
            4
          ],
          [
            2,
            5
          ],
          [
            2,
            6
          ]
        ],
        "label":"row=2"
      },
      {
        "actionId":3,
        "pieceType":"hori",
        "anchor":[
          3,
          0
        ],
        "mask":"266338304",
        "cells":[
          [
            3,
            0
          ],
          [
            3,
            1
          ],
          [
            3,
            2
          ],
          [
            3,
            3
          ],
          [
            3,
            4
          ],
          [
            3,
            5
          ],
          [
            3,
            6
          ]
        ],
        "label":"row=3"
      },
      {
        "actionId":4,
        "pieceType":"hori",
        "anchor":[
          4,
          0
        ],
        "mask":"34091302912",
        "cells":[
          [
            4,
            0
          ],
          [
            4,
            1
          ],
          [
            4,
            2
          ],
          [
            4,
            3
          ],
          [
            4,
            4
          ],
          [
            4,
            5
          ],
          [
            4,
            6
          ]
        ],
        "label":"row=4"
      },
      {
        "actionId":5,
        "pieceType":"hori",
        "anchor":[
          5,
          0
        ],
        "mask":"4363686772736",
        "cells":[
          [
            5,
            0
          ],
          [
            5,
            1
          ],
          [
            5,
            2
          ],
          [
            5,
            3
          ],
          [
            5,
            4
          ],
          [
            5,
            5
          ],
          [
            5,
            6
          ]
        ],
        "label":"row=5"
      },
      {
        "actionId":6,
        "pieceType":"hori",
        "anchor":[
          6,
          0
        ],
        "mask":"558551906910208",
        "cells":[
          [
            6,
            0
          ],
          [
            6,
            1
          ],
          [
            6,
            2
          ],
          [
            6,
            3
          ],
          [
            6,
            4
          ],
          [
            6,
            5
          ],
          [
            6,
            6
          ]
        ],
        "label":"row=6"
      }
    ]
  },
  "policyTable":{},
  "distilledPolicy":{
    "modelType":"linear_ranker_v1",
    "featureNames":[
      "bias",
      "filled_count",
      "remaining_count",
      "immediate_gain",
      "action_coverage",
      "action_edge_coverage",
      "action_corner_coverage",
      "new_edge_fill",
      "new_corner_fill",
      "result_filled_count",
      "row_completion_delta",
      "col_completion_delta",
      "max_row_fill_after",
      "max_col_fill_after",
      "touches_center",
      "touches_main_diag",
      "touches_anti_diag",
      "anchor_row",
      "anchor_col",
      "action_id_norm"
    ],
    "models":{
      "cross":{
        "weights":[
          0.0,
          0.0,
          0.0,
          1.17032612,
          -0.08079124,
          0.16289579,
          -0.0647627,
          -0.28601397,
          0.40107262,
          0.16718945,
          0.45146247,
          0.4151773,
          -0.10894095,
          -0.08299953,
          0.088187,
          -0.0077029,
          0.01397247,
          -0.0106336,
          -0.01768075,
          -0.0115145
        ],
        "examples":2408
      },
      "xshape":{
        "weights":[
          0.0,
          0.0,
          0.0,
          1.21936369,
          -0.06605401,
          0.12253382,
          -0.12107673,
          -0.26386525,
          0.03480474,
          0.17419481,
          0.45682702,
          0.41233259,
          0.0302547,
          0.03832029,
          0.06410979,
          -0.00913787,
          -0.01434311,
          -0.00606696,
          -0.00943315,
          -0.00648773
        ],
        "examples":2290
      },
      "square3":{
        "weights":[
          0.0,
          0.0,
          0.0,
          1.19946611,
          0.04574743,
          -0.13635967,
          0.12164418,
          0.25394744,
          -0.04977683,
          0.1713523,
          0.40129258,
          0.40086892,
          0.19280365,
          0.12691608,
          -0.04641533,
          -0.02430463,
          -0.01702181,
          -0.00396755,
          -0.00096919,
          -0.00359276
        ],
        "examples":2266
      },
      "vert":{
        "weights":[
          0.0,
          0.0,
          0.0,
          0.56499526,
          0.0,
          -0.11480698,
          -0.08036488,
          0.29465407,
          0.33933105,
          0.08071361,
          0.70952234,
          -0.07177861,
          -0.01014279,
          0.0,
          -0.05911101,
          0.0,
          0.0,
          0.0,
          0.00048725,
          0.00048725
        ],
        "examples":2584
      },
      "hori":{
        "weights":[
          0.0,
          0.0,
          0.0,
          0.65440135,
          0.0,
          -0.07765057,
          -0.0543554,
          0.26631466,
          0.20132672,
          0.09348591,
          0.11164299,
          0.80785236,
          0.0,
          -0.38270705,
          -0.06927365,
          0.0,
          0.0,
          -0.02328152,
          0.0,
          -0.02328152
        ],
        "examples":2132
      }
    }
  },
  "distilledValue":{
    "modelType":"linear_value_v1",
    "featureNames":[
      "bias",
      "filled_count",
      "remaining_count",
      "row_fill_0",
      "row_fill_1",
      "row_fill_2",
      "row_fill_3",
      "row_fill_4",
      "row_fill_5",
      "row_fill_6",
      "col_fill_0",
      "col_fill_1",
      "col_fill_2",
      "col_fill_3",
      "col_fill_4",
      "col_fill_5",
      "col_fill_6",
      "cross_gain_max",
      "xshape_gain_max",
      "vert_gain_max",
      "hori_gain_max",
      "cross_gain_mean",
      "xshape_gain_mean",
      "vert_gain_mean",
      "hori_gain_mean",
      "empty_region_count",
      "largest_empty_region",
      "edge_occupancy",
      "corner_occupancy",
      "center_occupancy",
      "diagonal_main",
      "diagonal_anti"
    ],
    "weights":[
      1.42864303,
      -0.14942495,
      1.57806798,
      -0.07384017,
      -0.29118939,
      0.09460914,
      -0.71678051,
      -0.04606773,
      0.02558305,
      -0.03828903,
      -0.09031124,
      0.07220064,
      0.12417092,
      -0.22913686,
      -0.53974311,
      -0.41158171,
      0.02842671,
      0.74052835,
      -1.04177338,
      1.15783913,
      1.18065601,
      1.00701619,
      0.90086631,
      1.57806798,
      1.57806798,
      1.92263393,
      -0.60934969,
      -0.08841575,
      0.22597046,
      -0.05726395,
      -0.87042402,
      -0.20695428
    ]
  },
  "symmetryEnabled":true,
  "runtimeMode":"mcts_puct_v1",
  "buildInfo":{
    "generatedAtUtc":"2026-03-31T04:10:09.277258+00:00",
    "policyVersion":"self_play_rl_only",
    "tableSize":0,
    "datasetRows":11680,
    "trainingMode":"self_play_rl",
    "apiConfig":{
      "numIterations":2,
      "samplingEpisodes":48,
      "maxSamples":192,
      "useSymmetry":true,
      "samplingEpsilon":0.05,
      "teacherEpisodes":16,
      "teacherMaxSamples":96,
      "seed":19
    },
    "distillConfig":{
      "seed":47,
      "valueEpochs":22,
      "valueLearningRate":0.08,
      "policyEpochs":14,
      "policyLearningRate":0.16
    },
    "runtimeConfig":{
      "searchDepth":2,
      "candidateK":6,
      "useSymmetry":true,
      "runtimeMode":"mcts_puct_v1",
      "exactReachableMaxStates":50000,
      "mctsNumSimulations":64,
      "mctsCPuct":1.35,
      "mctsDirichletAlpha":0.3,
      "mctsDirichletEpsilon":0.0,
      "mctsMaxDepth":3,
      "mctsExpandTopK":6,
      "mctsChanceMode":"enumerate"
    },
    "distillationSummary":{
      "rows":11680,
      "trainingMode":"self_play_rl",
      "distillConfig":{
        "seed":47,
        "valueEpochs":22,
        "valueLearningRate":0.08,
        "policyEpochs":14,
        "policyLearningRate":0.16
      },
      "iterations":[
        {
          "iteration":1,
          "episodes":96,
          "rows":1956,
          "mean_steps":10.1875
        },
        {
          "iteration":2,
          "episodes":96,
          "rows":3910,
          "mean_steps":10.1875
        },
        {
          "iteration":3,
          "episodes":96,
          "rows":5832,
          "mean_steps":10.010416666666666
        },
        {
          "iteration":4,
          "episodes":96,
          "rows":7768,
          "mean_steps":10.083333333333334
        },
        {
          "iteration":5,
          "episodes":96,
          "rows":9740,
          "mean_steps":10.270833333333334
        },
        {
          "iteration":6,
          "episodes":96,
          "rows":11680,
          "mean_steps":10.104166666666666
        }
      ],
      "config":{
        "numIterations":6,
        "selfPlayEpisodes":96,
        "maxSteps":512,
        "seed":59,
        "useSymmetry":true,
        "symmetryAugmentations":1,
        "mcts":{
          "numSimulations":96,
          "cPuct":1.35,
          "dirichletAlpha":0.3,
          "dirichletEpsilon":0.25,
          "maxDepth":3,
          "expandTopK":6,
          "chanceMode":"enumerate"
        }
      }
    },
    "history":[],
    "rlConfig":{
      "numIterations":6,
      "selfPlayEpisodes":96,
      "maxSteps":512,
      "seed":59,
      "useSymmetry":true,
      "symmetryAugmentations":1,
      "mctsNumSimulations":96,
      "mctsCPuct":1.35,
      "mctsDirichletAlpha":0.3,
      "mctsDirichletEpsilon":0.25,
      "mctsMaxDepth":3,
      "mctsExpandTopK":6,
      "mctsChanceMode":"enumerate"
    },
    "pieceProbabilities":{
      "cross":0.250996015936255,
      "xshape":0.250996015936255,
      "square3":0.1394422310756972,
      "vert":0.17928286852589642,
      "hori":0.17928286852589642
    }
  },
  "pieceProbabilities":{
    "cross":0.250996015936255,
    "xshape":0.250996015936255,
    "square3":0.1394422310756972,
    "vert":0.17928286852589642,
    "hori":0.17928286852589642
  }
};
